networks:
  ticketIt-app:

services:
  app:
    container_name: ticket-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:4000"
    depends_on:
      - "postgres"
    networks:
      - ticketIt-app

  postgres:
    container_name: ticket-api-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ticket_it
      POSTGRES_DB: ticket_it
      POSTGRES_PASSWORD: password123
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_ticketit-api-data:/var/lib/postgresql/data

volumes:
  pg_ticketit-api-data:
